# Generated by Django 4.0.10 on 2024-04-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='location',
            name='category',
        ),
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(to='core.category'),
        ),
        migrations.AlterField(
            model_name='map',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
