# Generated by Django 4.0.10 on 2024-04-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_name',
            new_name='name',
        ),
    ]
