# Generated by Django 4.0.10 on 2024-05-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_favorite_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_locations',
            field=models.ManyToManyField(blank=True, related_name='favorite_locations', to='core.location'),
        ),
    ]
