# Generated by Django 4.0.10 on 2024-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_favorite_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_locations',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_locations',
            field=models.TextField(blank=True),
        ),
    ]
