# Generated by Django 4.0.10 on 2024-06-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_lesson_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coupon_received_locations',
            field=models.ManyToManyField(blank=True, related_name='coupon_received_locations', to='core.location'),
        ),
    ]
